# Generated by Django 4.1.2 on 2022-10-19 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2787f4b5-e96e-4618-990c-dbc28ed19516'), editable=False, unique=True),
        ),
    ]
