# Generated by Django 4.1.2 on 2022-10-19 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb50dc86-9960-4b08-98c9-33f2bf798d31'), editable=False, unique=True),
        ),
    ]
