# Generated by Django 4.1.2 on 2022-10-19 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66b8494b-fe03-430f-8bf2-bda7838a9d75'), editable=False, unique=True),
        ),
    ]
