# Generated by Django 4.1.2 on 2022-10-19 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3820d529-a150-4dcf-85ae-8217dc635017'), editable=False, unique=True),
        ),
    ]
