# Generated by Django 4.1.2 on 2022-10-19 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e572d3d7-4a75-43f7-8a06-f374dd34a48b'), editable=False, unique=True),
        ),
    ]
